import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        firefly: {
          "5": "#73787A",
          "50": "#f9f9fa",
          "100": "#edf0f2",
          "200": "#B7BEC1",
          "300": "#9FA9AC",
          "400": "#879397",
          "500": "#6F7E83",
          "600": "#57696E",
          "700": "#3F5359",
          "800": "#273E45",
          "900": "#0F2830",
          "950": "#09181D",
          DEFAULT: "#0F2830",
        },
        teal: {
          "5": "#F2FDFA",
          "50": "#E7FCF8",
          "100": "#DBFBF5",
          "200": "#C4F8EF",
          "300": "#AEF5E8",
          "400": "#97F3E2",
          "500": "#80F0DB",
          "600": "#69EDD5",
          "700": "#53EACF",
          "800": "#3CE8C8",
          "900": "#25E5C2",
          "950": "#1AD7B4",
          DEFAULT: "#25E5C2",
        },
        "neon-blue": {
          "10": "#F2FAFB",
          "50": "#D1F6F9",
          "100": "#C6F4F7",
          "200": "#AFF0F4",
          "300": "#99ECF1",
          "400": "#83E8EE",
          "500": "#6CE3EB",
          "600": "#56DFE8",
          "700": "#3FDBE5",
          "800": "#29D7E2",
          "900": "#1DC9D4",
          "950": "#1AB4BE",
          DEFAULT: "#1DC9D4",
        },
        "neon-green": {
          "50": "#ECFCF6",
          "100": "#E1FBF0",
          "200": "#CBF8E5",
          "300": "#B4F5DA",
          "400": "#9EF2CF",
          "500": "#88EEC4",
          "600": "#71EBB8",
          "700": "#5BE8AD",
          "800": "#44E5A2",
          "900": "#2EE297",
          "950": "#1ED88B",
          DEFAULT: "#2EE297",
        },
        raspberry: {
          "10": "#FDF3F5",
          "30": "#F7CAD3",
          "50": "#FCE2E9",
          "100": "#FBD8E3",
          "200": "#F9C6D5",
          "300": "#F7B4C8",
          "400": "#F5A1BA",
          "500": "#F38FAD",
          "600": "#F17C9F",
          "700": "#EF6A92",
          "800": "#ED5784",
          "900": "#EB4577",
          "950": "#E92E66",
          DEFAULT: "#EB4577",
        },
        purple: {
          "10": "#F5F5FF",
          "30": "#D3D6FF",
          "50": "#F9FAFF",
          "100": "#F1F3FF",
          "200": "#E2E5FF",
          "300": "#D3D7FF",
          "400": "#C4C9FF",
          "500": "#B4BBFF",
          "600": "#A5ADFF",
          "700": "#969FFF",
          "800": "#8691FF",
          "900": "#7783FF",
          "950": "#5E6CFF",
          DEFAULT: "#7783FF",
        },
        green: {
          "10": "#F2FCF7",
          "40": "#A5EEC7",
          "80": "#24AF75",
          DEFAULT: "#24AF75",
        },
        neutral: "#e0e0e0",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        slideDown: {
          "0%": { maxHeight: "0", opacity: "0", overflow: "hidden" },
          "100%": { maxHeight: "1000px", opacity: "1", overflow: "visible" },
        },
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        slideDown: "slideDown 0.5s ease-in-out forwards",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
